### ISSUE TITLE
Set up ssl on site

### ISSUE THREAD

**Issue by gabelula** [kboofm/kboo.fm#1]
@troff commented on [Fri Jun 24 2016](https://github.com/kboofm/old-kboo.fm/issues/10)

Use https://letsencrypt.org/ for certificate to implement ssl on kboo.fm

**Comment by troff** [comment]
fixed! finally. used letsencrypt.org with certbot on shell, for future reference....

**Comment by gabelula** [comment]
oh yeah! Congratulations!

2017-08-31 13:03 GMT-07:00 j. funk <notifications@github.com>:
