### ISSUE TITLE
Book pages

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#13]
We need to adjust the Book pages so that the sub-pages of each COmmittee page show up - ie. a list of the meeting minutes for each committee. Also need to adjust the sorting so that it sorts chronologically, with the most recent date first - and the titles of each of the book pages need to be standardized so that they will show up in the correct order.
Right now they are using 'weight', but we have reached the limit of 30 items on some of the book pages (ie. Finance Committee http://kboo.fm/finance-committee )

**Comment by troff** [comment]
The directory listing in this screen shot would be good - but it only shows up when you go in as an editor to edit a book page.
![committee list from admin page](https://cloud.githubusercontent.com/assets/4783226/20172621/adbc0c6a-a6ea-11e6-9069-ce152a2f96ea.png)

as a user, you only see this:
![committee listing on book page](https://cloud.githubusercontent.com/assets/4783226/20172630/b9d10136-a6ea-11e6-9b87-8df498d68b8e.png)

**Comment by beefman1** [comment]
I'll need to look more into this.  Do you want the full outline visible on every book page?  Or only so many levels deeper than the current page?

**Comment by troff** [comment]
Just the levels deeper than the current page.
It would be great, however, if the 'outline' link did actually lead to a full outline of the book, if people want to go there.

**Comment by beefman1** [comment]
added the sublevel to live.  Waiting to hear from you on the full outline page visible at http://xdev.kboo.fm/booktree

**Comment by troff** [comment]
yes - let's make the fill outline listing visible on the live site, on the 'About KBOO' page - like you have it on this page:
http://xdev.kboo.fm/booktree

**Comment by beefman1** [comment]
That is now in place on live at http://kboo.fm/booktree
