### ISSUE TITLE
Adding image files inline using wysywig editor is not working

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#14]
The only way to add an image file in the node creation form is on the left side menu 'add media'. there is an image icon in the wysywig editor but it is not working, nothing happens when a user clicks on the icon to add an image.

**Comment by beefman1** [comment]
The image tool wasn't active on live.  I added it to dev, see here: http://xdev.kboo.fm/node/add/basic-page on the far right of the top row and tested.  Worked ok so i put it on live as well for those content types using Full HTML + Advanced WYSIWYG.  If you want it on simple wysiwyg as well let me know.  Closing.
