### ISSUE TITLE
Drupal core and other updates

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#15]
Drupal core needs updating and there are some other security updates. The documentation for updating Drupal core is here: https://github.com/kboofm/kboo.fm/blob/master/docs/files/KBOOD7-UpdatingDrupalcore-060516.pdf

Must be tested on dev first.... #

**Comment by beefman1** [comment]
Ok.  I've updated xdev, but a couple questions.

1) The file patches/core/delete-robots-txt.patch is a diff w/ /dev/null, so it deletes robots.txt (as the name suggests).  But that patch file doesn't match the existing robots.txt so gives an error.  I moved the file out of the web root for that site.

2) Do you have tests you want to run on it before moving live?

**Comment by troff** [comment]
1. Is there a reason robots.txt is there? it installs when drupal core was updated? I think it's fine to just remove it manually as you did.
2. yes - I will run the QA testing on xdev
   this is our QA testing procedure:
   https://sites.google.com/a/kboo.org/kboo-website-documentation/qa-testing

**Comment by beefman1** [comment]
1.  Yes, robots.txt is in the core tarball.
2.  Ok, let me know when you're done.

**Comment by beefman1** [comment]
Can you share that doc or email it, or will i have anything to do with 
testing?

**Comment by troff** [comment]
I have completed testing - ready to push to live (just doublecheck the donate and listen buttons, make sure they don't disappear

**Comment by beefman1** [comment]
I pushed this live and updated the db, but there is a new core update (7.52) and an update to bootstrap.  Once i'm done with the rest i will put those on dev.

**Comment by beefman1** [comment]
updated dev to 7.53 the other night.
