### ISSUE TITLE
'Lead image' sizing on program and episode pages

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#16]
The 'lead image' on program and episode pages 
![program pages lead image](https://cloud.githubusercontent.com/assets/4783226/20172143/a74b40dc-a6e8-11e6-8aa8-aeb74b20b38c.png)
is sized at 300 x 225 px
But instead of resizing images that are posted, the theme just zooms in on the center 300x225px
which means in a lot of cases, large parts of the image are cut off.

I'd prefer a square resizing -- or view: - Itunes requires images that are 1200x1200 - though that wouldn't fit on a page, the view on the page could be set to 300 x 300 px or so, and the image itself the larger size to make Itunes happy.

**Comment by beefman1** [comment]
I changed this preset to "scale" to 300x300 from "scale and crop" to 300x225.  Here's how the same looks: http://xdev.kboo.fm/media/50320-criminalization-produced-center-intercultural-organizing

You may want to try a few others with differing aspect ratios.  Lemme know if you want this live.

**Comment by troff** [comment]
yes!! please make it live :)

**Comment by beefman1** [comment]
I set this on live.
