### ISSUE TITLE
Adding list of user's audio to their profile page

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#17]
In our Drupal 6 site, when viewing a user's profile page, there would be a list of all the audio and content authored by that user.
That functionality disappeared in the migration to D7, and is something that we want to have restored.

**Comment by beefman1** [comment]
http://xdev.kboo.fm/profiles/andy-hosch  on dev.  this only shows the linked episode titles.  Lemme know whether you want it restyled, want a pager, want additional fields, etc.

**Comment by troff** [comment]
Yes - if the display could look like the display list on the program pages (thumbnail, excerpt with read more link, pager at the bottom)..... that would be great. (ex. http://kboo.fm/program/old-mole-variety-hour )  -- one question about these listings, whether on program pages, user profiles or front page - how hard is it to get the audio player to appear in the excerpt? On the old D6 site, the player appeared on each listed item, was easier for users to access the audio, which is what we really want....

**Comment by beefman1** [comment]
for future reference so i don't have to locate it again:  radio_station.module, fn radio_station_preprocess_radio_template_program_content_list

Then /lib/components/StationContentComponent create a clone of getContentForProgram using my query params and returning similar;  place call to it in /lib/responses/ProgramResponse clone of getContent

I'm looking to see whether i can use existing rendering code to make this easy and keep them identical to one another.

**Comment by beefman1** [comment]
[master 6eee74c]   ---  made this work using the same scheme as the program content list.  It appears on profile pages on dev now.

Looking into putting the player in now.

**Comment by beefman1** [comment]
Try this on dev.  Here is a sample host page: http://xdev.kboo.fm/profiles/andy-hosch   I added audio clips to the top 4 hits so you could see that it works.  Compare http://xdev.kboo.fm/media/53717-art-kora

[master 6fd2a15]

**Comment by troff** [comment]
yes -this looks good.
can be pushed to live whenever you have a
chance.

is that list display, with the audio player included,
available for the Latest Audio page too, and the program pages?

thank you! how are you doing time-wise?

thx
jenka

> Try this on dev.  Here is a sample host page:
>
http://xdev.kboo.fm/profiles/andy-hosch   I added audio clips to the top
4
> hits so you could see that it works.  Compare
>
http://xdev.kboo.fm/media/53717-art-kora
> 
> [master
6fd2a15]
> 
> --
> You are receiving this because
you authored the thread.
> Reply to this email directly or view it
on GitHub:
>
https://github.com/kboofm/kboo.fm/issues/17#issuecomment-269817143

**Comment by beefman1** [comment]
Jenka,

Are the other changes acceptable as well?  I haven't pushed to live in a 
while, so several have accumulated.  In particular the updates and the 
css change for the radio buttons might cause issues.  Are you 
comfortable with those going live?

Timewise it took forever to tool that listing around the existing stuff 
so i'm just shy of 10, but made adding to program pages a cinch so 
that's done now too on dev.

Darin

**Comment by troff** [comment]
hmm, and i don't suppose that fixing the timeslot/scheduling issue will fit in under 10 hours. i can authorize 2 - 3 more hours to try to fix the timeslot thing.
i will test the changes, and let u know when to push them live


I apologize for any typos, this was sent on a mobile device
-------- Original message --------From: beefman1 <notifications@github.com> Date: 12/31/16  12:15 PM  (GMT-08:00) To: "kboofm/kboo.fm" <kboo.fm@noreply.github.com> Cc: troff <jenka@resist.ca>, Author <author@noreply.github.com> Subject: Re: [kboofm/kboo.fm] Adding list of user's audio to their profile
  page (#17) 
Jenka,



Are the other changes acceptable as well?  I haven't pushed to live in a 

while, so several have accumulated.  In particular the updates and the 

css change for the radio buttons might cause issues.  Are you 

comfortable with those going live?



Timewise it took forever to tool that listing around the existing stuff 

so i'm just shy of 10, but made adding to program pages a cinch so 

that's done now too on dev.



Darin

**Comment by beefman1** [comment]
Jenka,

I plan to take a look at this this afternoon.  Will let you know how 
much time it looks like then.

Thanks,
Darin
