### ISSUE TITLE
Chromecast issues with 'listen now' popup

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#19]
The Listen Now link opens up a new window with the player in it.
This window has no toolbar and thus does not have the chromecast link in it
so it can be played on a chromecast.  I imagine I'm not the only one who
listens to KBOO over the internet through a chromecast.  I'm sure a slight tweak in the
open new window parameters would fix that.

**Comment by beefman1** [comment]
i changed it to have the toolbar & menubar.  Lemme know whether this works on chromecast on dev.

[master 91db3b7] added toolbar & menubar to listen now popup

**Comment by troff** [comment]
yes - please push to live.
