### ISSUE TITLE
Latest audio page

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#20]
The 'Latest audio' and 'recent playlists' pages should be populated with the same content as the sidebars with the same name. But should include titles, teasers and links for 'Latest audio', and Program name and link in addition to playlist info, for the 'recent playlists' page.
http://kboo.fm/audio
http://kboo.fm/program/playlists

**Comment by troff** [comment]
So the 'recent audio' page does have the same content as the sidebar, but the sidebar was changed to exclude any audio for future dates, only today's date and earlier audio should be displayed on this page (just like the sidebar).

**Comment by beefman1** [comment]
Recent audio now matches the sidebar on dev.

I see the same content on the playlist page and the sidebar.

[master e15563b] fix to make recent audio page match sidebar

**Comment by troff** [comment]
Looks good.
Please push to live - also please add the audio player in the 'Recent audio' listings - like in:
https://github.com/kboofm/kboo.fm/issues/17
