### ISSUE TITLE
'contact us' and other pages radio buttons

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#21]
on chrome, firefox, and safari the radio buttons on this contact-us page and other web forms overwrite the first letter of the title of the Category.

**Comment by beefman1** [comment]
http://xdev.kboo.fm/contact-us
I fixed it there in as unobtrusive a manner as i could.  Are there other instances?  Please lemme know or lemme know if you see any errors introduced.

[master d8d8e8b] fix to contact us radio buttons

**Comment by troff** [comment]
Looks fine - please push to live. thanks!
