### ISSUE TITLE
Recent playlists page

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#22]
the display of this page:
http://kboo.fm/program/playlists
pulls from the spinitron "last 99 songs" api.
but it has no separation of playlists based on program

the desired display should either include the embedded playlists, but separated by program,
or just have links to the program episodes that contain playlists.
![recent-playlist-page](https://cloud.githubusercontent.com/assets/4783226/21780482/a4e91ccc-d660-11e6-9f75-9f38aff3536a.png)

**Comment by beefman1** [comment]
http://xdev.kboo.fm/program/playlists

I am able to put the program name in, and i added it to the list + a blank line between the programs.  What do you think?

**Comment by troff** [comment]
I mean - ideally it would have the program name above that show's playlist (with a link to the program episode page for that time).

As for the twitter share and 'buy it now' buttons, this is how they look on the spinitron site:
![spinitron playlist 2017-01-17 03 36 26](https://cloud.githubusercontent.com/assets/4783226/22019007/74676610-dc66-11e6-8d86-9cf56388de39.png)

**Comment by beefman1** [comment]
Ok, try now.  What is the twitter screenshot about?

**Comment by beefman1** [comment]
Ok made more changes to this to add the links & not use so much js.  Try now in case you did earlier and didn't see the links.

**Comment by troff** [comment]
can you send me the list of commands you use for pushing to github?i have used svn and feel like i could learn the process to push to live pretty easily,  just not sure of the exact commands. 
thanks! jenka


I apologize for any typos, this was sent on a mobile device
-------- Original message --------From: beefman1 <notifications@github.com> Date: 1/17/17  6:53 PM  (GMT-08:00) To: "kboofm/kboo.fm" <kboo.fm@noreply.github.com> Cc: troff <jenka@resist.ca>, Author <author@noreply.github.com> Subject: Re: [kboofm/kboo.fm] Recent playlists page (#22) 
Ok made more changes to this to add the links & not use so much js.  Try now in case you did earlier and didn't see the links.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kboofm/kboo.fm","title":"kboofm/kboo.fm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kboofm/kboo.fm"}},"updates":{"snippets":[{"icon":"PERSON","message":"@beefman1 in #22: Ok made more changes to this to add the links \u0026 not use so much js.  Try now in case you did earlier and didn't see the links.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/kboofm/kboo.fm/issues/22#issuecomment-273368711"}}}

**Comment by beefman1** [comment]
Jenka,

Yes.

For adding changes to the working directory:

In the working dir, say you edit file1 and file2.  You can say "git 
status" to see what files are changed, and you'll see file1 and file2.  
If you want to see the actual changes, "git diff file1" or "git diff 
file2" will show you the diffs.

Then "git add file1" to stage the changes to file1, then 'git commit 
-m"<my commit message>"' to commit it with whatever commit message you 
want (this shows up next to that commit when you type git log).

Then to push to the repo, you type git push.  To pull into the other 
repo (eg live), you cd into the live working directory and type git pull.

I hope this helps...  If anything doesn't make sense lemme know.

Darin
