### ISSUE TITLE
Formatting of save/edit buttons

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#23]
During the last drupal core update, the formatting of the save/edit buttons (when a user goes in to edit any page) has been lost. see screenshots below. The top one is incorrect, the bottom one is correct.
![buttons-wrong-formatting](https://cloud.githubusercontent.com/assets/4783226/21780744/9d6f687e-d661-11e6-9a1f-6364975a23c8.png)
![buttons-correct-formatting](https://cloud.githubusercontent.com/assets/4783226/21780764/b5d7ba24-d661-11e6-9ce5-eaa0d0633170.png)

**Comment by beefman1** [comment]
This is fixed by disabling "aggregate & compress css files" here: http://kboo.fm/admin/config/development/performance

Looks buggish and like a rabbit hole so will leave it on for now and look more into it after i look at the playlist issue.

**Comment by troff** [comment]
disabled it - hoping it doesn't have any other adverse effects...
