### ISSUE TITLE
Program pages - coming soon box

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#24]
The 'coming soon' box on Program pages only appears when there is an upcoming episode scheduled.
On the old D6 site, it would always appear - when there was no episode scheduled, it would just list the next time the program airs, with no hyperlink.

Also it would be good to move the 'subscribe to podcast' link over to that box, with a graphic image instead of a text link, so it stands out.
The podcast links are all the same:
`http://kboo.fm/program/[programname]/podcast`

this is the box I am talking about:
![program-page-listing-upcoming-show](https://cloud.githubusercontent.com/assets/4783226/21791879/d671ccd2-d69a-11e6-8879-b79007d44f82.png)

**Comment by beefman1** [comment]
this is on dev.

**Comment by troff** [comment]
hi @beefman1 will you have time to update it to live today? otherwise we have to wait til next week after the fund drive (ends dec. 4th) thanks.

**Comment by beefman1** [comment]
Ok to push live now?

**Comment by troff** [comment]
yes yes to live!
