### ISSUE TITLE
Copy/pasted text is black on dark teal

### ISSUE THREAD

**Issue by BMeiers** [kboofm/kboo.fm#25]
Is it possible to have some of the formatting removed from text copied, then pasted, from the website? Right now, text from the website put into Word (and perhaps other applications,) is black on a dark teal background. Any way we can remove the background teal from copied text?

![web text](https://cloud.githubusercontent.com/assets/24534536/23776218/ce8df00c-04e1-11e7-833e-6cb00804f5a5.PNG)

**Comment by troff** [comment]
ok, should be fixed - give it a try and let me know if it's still happening.

**Comment by BMeiers** [comment]
It's fixed on my Mac; I'll check in when I'm at the station if it's fixed
on my PC! Thank you!


[image: signature logo_evergreen.png]
<https://interland3.donorperfect.net/weblink/weblink.aspx?name=E9988&id=1>

Becky Meiers, Development Director

pronouns she/them

KBOO-FM | (503) 231-8032, ext. 219

20 SE 8th Ave., Portland, OR 97214

development@kboo.org | kboo.fm/give
<https://interland3.donorperfect.net/weblink/weblink.aspx?name=E9988&id=1>

Join KBOO — help revolutionize the media.
<https://interland3.donorperfect.net/weblink/weblink.aspx?name=E9988&id=1>

[image: facebook logo (1).png] <https://www.facebook.com/kbooradio/>  [image:
twitter logo (1).jpg] <https://twitter.com/KBOO>  [image: instagram-vetor1
(1).png] <https://www.instagram.com/kbooradio/>
