### ISSUE TITLE
Wrong playlist attached to my show

### ISSUE THREAD

**Issue by Efschwartz** [kboofm/kboo.fm#31]
I created a playlist for the Portland Jewish Hour's 7/9 show today on Spinitron, but it's not attaching to the audio of that show which is appearing on the Jewish Hour site. Instead, we've got a playlist from yesterday's True Vine, I think. Please fix asap! Thanks.

**Comment by troff** [comment]
ok I fixed it, sorry for taking so long!!
the Music from the True Vine folks had put the wrong date on their playlist.
http://kboo.fm/media/59067-portland-jewish-hour
