### ISSUE TITLE
Can't add images through wysiwyg editor

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#32]
Program hosts and other site users need to be able to add images and other content through the wysiwyg editor, but this is not currently allowed. also can't place images in layout of the page.

**Comment by beefman1** [comment]
Added imce to ckeditor config here: https://xdev.kboo.fm/admin/config/content/ckeditor/edit/Full_HTML_Advanced

Check it here, for example: https://xdev.kboo.fm/node/61508/edit

screenshot attached.
![ss1](https://user-images.githubusercontent.com/14895568/34427954-9b510848-ec15-11e7-9ff7-17247a465fea.png)

**Comment by beefman1** [comment]
btw that's on dev.  If it fixes the problem lemme know and i will do it on live.

**Comment by troff** [comment]
yes except the permissions issue I emailed, other than that it is fine to push to live

**Comment by beefman1** [comment]
Added that to live with perms for admin-developer role.
