### ISSUE TITLE
Main rss feed for site needs to have <enclosure> tag added

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#35]
The "Latest Audio" section uses the following feed"
https://kboo.fm/audio/feed

If you load that feed in your browser you will notice each item in the feed does not include any audio files.

It needs to have <enclosure> tags added to include the mp3 files.

**Comment by beefman1** [comment]
i added a makeshift file link to the field template.  adding an enclosure element as in the other rss feed page didn't work.  check http://xdev.kboo.fm/audio/feed and let me know whether you want it live.  compare with http://xdev.kboo.fm/program/kitchen-table-conversations/podcast

**Comment by beefman1** [comment]
Ok i made it use the same processor as the other feed.  It validates now and matches the other feed.  Compare http://xdev.kboo.fm/audio/feed with http://xdev.kboo.fm/program/kitchen-table-conversations/podcast

**Comment by troff** [comment]
thanks @beefman1 ! one thing I noticed on the live site feed - the title of the page appears to be reflecting the first item in the feed.
But since this is a feed of ALL programs the title should instead be KBOO Community Radio
see:
<channel>
    <title>KBOO Stage and Studio</title>
    <atom:link href="https://kboo.fm/program/stage-and-studio/podcast" rel="self" type="application/rss+xml"/>
    <link>https://kboo.fm/program/stage-and-studio</link>

on: https://kboo.fm/audio/feed

**Comment by beefman1** [comment]
ok i fixed that.

**Comment by troff** [comment]
fixed thanks @beefman1
