### ISSUE TITLE
Timeslot 5th week issue

### ISSUE THREAD

**Issue by troff** [kboofm/kboo.fm#36]
I am trying to create a timeslot for the 5th week of the month 10 pm - midnight -- the site indicates that there's a conflict with an existing timeslot -- but when I look at that existing timeslot it does not overlap - it is for the FIRST week of the month 10 pm - midnight.
I wonder why the site thinks there is a conflict?
![20170609 timeslot 10pm - midnight](https://user-images.githubusercontent.com/4783226/29019198-bd3d735c-7b12-11e7-9076-2ec7d95cc534.png)
![20170609 timeslot 10pm - midnight first week of the month](https://user-images.githubusercontent.com/4783226/29019202-be03573e-7b12-11e7-909a-c76921238a32.png)

**Comment by beefman1** [comment]
I found the issue and posted a fix on drupal.org.  Will wait a week or so to see whether maintainers run tests on it to decide whether to move to live.  If they post a better fix we'll use that.

https://www.drupal.org/project/date/issues/2900532

**Comment by beefman1** [comment]
but my fix is on dev so play with it if you want.

**Comment by troff** [comment]
yes, this seems to have worked - so go ahead and push it to live.
![cascadiacoffeehouse](https://user-images.githubusercontent.com/4783226/34444138-d3592994-ec80-11e7-9b0d-b3a48e471dfb.png)

**Comment by beefman1** [comment]
Ok.  for record, it passed the module's tests on this issue: https://www.drupal.org/project/date/issues/2900532

I made one more commit to make the code here match the final patch there that follows coding standards.  Just pushed live.

**Comment by troff** [comment]
yes I tested it - please push to live.
