### ISSUE TITLE
Fix the formatting and location of the ‘More content from this show’ link

### ISSUE THREAD

**Issue by gabelula** [kboofm/kboo.fm#4]
@gabelula commented on [Sat Jun 04 2016](https://github.com/kboofm/old-kboo.fm/issues/3)

**Comment by beefman1** [comment]
Where is this link?  How do you want it to look?

**Comment by beefman1** [comment]
This is fixed on dev.  Lemme know if it's acceptable & i'll push to live.

**Comment by troff** [comment]
yes! please push to live :)

**Comment by beefman1** [comment]
done.
