### ISSUE TITLE
Default schedule episode to ‘music - do not display download link'

### ISSUE THREAD

**Issue by gabelula** [kboofm/kboo.fm#7]
@gabelula commented on [Sat Jun 04 2016](https://github.com/kboofm/old-kboo.fm/issues/6)

---

@troff commented on [Fri Jun 10 2016](https://github.com/kboofm/old-kboo.fm/issues/6#issuecomment-225125697)

apparently must be done in database - see attached screenshot
![episode_recodring_download_link](https://cloud.githubusercontent.com/assets/4783226/15958829/aaf0f808-2eac-11e6-80b6-b4ab26146165.png)

---

@gabelula commented on [Fri Jun 10 2016](https://github.com/kboofm/old-kboo.fm/issues/6#issuecomment-225180456)

You can't change the types of recording for the episodes because you already have data in the database.  But you don't want to change that, right? You only want to change the eposides to type 0 or 1, right? Can you explain a little more here.

---

@troff commented on [Sat Jun 11 2016](https://github.com/kboofm/old-kboo.fm/issues/6#issuecomment-225402840)
# Expected behavior

When the user goes to create a new 'Program episode or audio', the webform should default to 'Public affairs program (display download link)
# current behavior

The webform defaults to 'Do not record this program' - and so the audio does not get recorded.

**Comment by beefman1** [comment]
Set on xdev & live.

**Comment by beefman1** [comment]
changed on live and xdev to "music (do not display download link)" per title here and email from Jenka dated 11/10/16 at 4:43 am.
